-- auto Generated on 2020-01-08
-- DROP TABLE IF EXISTS myshop.tb_content;
CREATE TABLE myshop.tb_content(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	category_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '内容类目ID',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT '内容标题',
	sub_title VARCHAR (50) NOT NULL DEFAULT '' COMMENT '子标题',
	title_desc VARCHAR (50) NOT NULL DEFAULT '' COMMENT '标题描述',
	url VARCHAR (50) NOT NULL DEFAULT '' COMMENT '链接',
	pic VARCHAR (50) NOT NULL DEFAULT '' COMMENT '图片绝对路径',
	pic2 VARCHAR (50) NOT NULL DEFAULT '' COMMENT '图片2',
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	content VARCHAR (50) NOT NULL DEFAULT '' COMMENT '内容',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'myshop.tb_content';
