-- auto Generated on 2020-01-08
-- DROP TABLE IF EXISTS myshop.tb_item_desc;
CREATE TABLE myshop.tb_item_desc(
	item_id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '商品ID',
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	item_desc VARCHAR (50) NOT NULL DEFAULT '' COMMENT '商品描述',
	PRIMARY KEY (item_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'myshop.tb_item_desc';
