-- auto Generated on 2020-01-08
-- DROP TABLE IF EXISTS myshop.tb_item;
CREATE TABLE myshop.tb_item(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '商品id，同时也是商品编号',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT '商品标题',
	sell_point VARCHAR (50) NOT NULL DEFAULT '' COMMENT '商品卖点',
	price BIGINT (15) NOT NULL DEFAULT -1 COMMENT '商品价格，单位为：分',
	num INT (11) NOT NULL DEFAULT -1 COMMENT '库存数量',
	barcode VARCHAR (50) NOT NULL DEFAULT '' COMMENT '商品条形码',
	image VARCHAR (50) NOT NULL DEFAULT '' COMMENT '商品图片',
	cid BIGINT (15) NOT NULL DEFAULT -1 COMMENT '所属类目，叶子类目',
	`status` TINYINT (3) NOT NULL DEFAULT 0 COMMENT '商品状态，1-正常，2-下架，3-删除',
	created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
	updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'myshop.tb_item';
