version: "3"
services:
  myshop-service-user-provider:
    restart: always
    image: 192.168.10.11:8082/dubbo-myshop/myshop-service-user-provider:v1.0.0
    container_name: myshop-service-user-provider_v1.0.0
    ports:
      - 8501:8501
      - 22222:22222
      - 20881:20881

networks:
  default:
    external:
      name: dubbo_myshop