# Spring boot application
spring:
  application:
    name: myshop-service-content-provider
  datasource:
    druid:
      url: jdbc:mysql://192.168.10.31:3307/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.10.32:26379, 192.168.10.32:26380, 192.168.10.32:26381
server:
  port: 8502

# MyBatis Config properties
mybatis:
  type-aliases-package: com.fun.uncle.myshop.commons.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true # 开启mybatis的二级缓存

# Services Versions
services:
  versions:
    content:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  ## Base packages to scan Dubbo Component：@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.fun.uncle.myshop.service.content.provider.api.impl
  ## ApplicationConfig Bean
  application:
    id: myshop-service-content-provider
    name: myshop-service-content-provider
    qos-port: 22223
    qos-enable: true
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
    status: server
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://192.168.10.33:2181?backup=192.168.10.33:2182,192.168.10.33:2183

# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool